### ISSUE TITLE
Platform compatibility

### ISSUE THREAD

**Issue by Kobzol** [spirali/qit#3]
Do we assume 32-bit compatibility? The current implementation is not 32-bit compatible (for example struct size in qit.base.vector expects size_t to have 8 bytes, while it only has 4 bytes on 32-bit platforms).

**Comment by spirali** [comment]
We support 32-bit architecture. The mentioned problem is a mistake in vector.py. Generally, we should use native types for given architecture. Since our C++ codes are run-and-forget programs, we do not have to consider platform-independent types.

I am also thinking about introducing some kind of `qint` (= qit-int) that will be used everywhere in C++ as integer type. The user can then change integer type in Qit constructor.
e.g. `ctx = Qit(qint_size=32)` defines of qint as `int32_t` and modifies deserialization functions in Python to read 32-bit values.

**Comment by spirali** [comment]
Problem with the vector size was fixed in 71a286c. Vector now serializes its size through qit.base.int.Int serialization.
